version: 2.1

executors:
  docker:
    docker:
      - image: circleci/node:lts
    environment:
      TZ: /usr/share/zoneinfo/America/Los_Angeles

commands:
  setup_yarn:
    steps:
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-node-{{ arch }}-{{ .Branch }}-
            - v2-node-{{ arch }}-
      - run:
          name: Install Packages
          command: yarn --frozen-lockfile
      - save_cache:
          name: Save node_modules cache
          key: v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  record_stats:
    steps:
      - run:
          name: Install sysstat
          command: sudo apt-get install --yes sysstat
      - run:
          name: Recording via sysstat
          background: true
          command: sudo /usr/lib/sysstat/sadc 5 -
  
  publish_stats:
    steps:
      - run: |
          sar -A
          sadf -g -O autoscale,skipempty -- -A > /tmp/sysstat.svg
      - store_artifacts:
          path: /tmp/sysstat.svg
          
jobs:
  yarn_test:
    executor: docker

    steps:
      - record_stats
      - checkout
      - setup_yarn
      - run:
          environment:
            RELEASE_CHANNEL: stable
          command: yarn test --maxWorkers=2
      - publish_stats

workflows:
  stable:
    jobs:
      - yarn_test