version: 2.1

executors:
  docker:
    docker:
      - image: circleci/node:lts
    environment:
      TZ: /usr/share/zoneinfo/America/Los_Angeles

commands:
  restore_yarn_cache:
    steps:
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-node-{{ arch }}-{{ .Branch }}-
            - v2-node-{{ arch }}-
  - run_yarn:
      steps:
        - run:
            name: Install Packages
            command: yarn --frozen-lockfile

jobs:
  setup:
    executor: docker

    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - restore_yarn_cache
      - run_yarn
      - save_cache:
          name: Save node_modules cache
          key: v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  RELEASE_CHANNEL_stable_yarn_test:
    executor: docker

    steps:
      - checkout
      - restore_yarn_cache
      - run_yarn
      - run:
          environment:
            RELEASE_CHANNEL: stable
          command: yarn test --maxWorkers=2

workflows:
  stable:
    jobs:
      - setup
      - RELEASE_CHANNEL_stable_yarn_test:
          requires:
            - setup